//------------------------------------------------------------------------------
// <copyright file="Resources.Designer.cs" company="Aras Corporation">
//     © 2017-2018 Aras Corporation. All rights reserved.
// </copyright>
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aras.VS.MethodPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16x16_delete {
            get {
                object obj = ResourceManager.GetObject("16x16-delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addLinkDialogDeleteItemLinkImg {
            get {
                object obj = ResourceManager.GetObject("addLinkDialogDeleteItemLinkImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addLinkDialogShowItemImg {
            get {
                object obj = ResourceManager.GetObject("addLinkDialogShowItemImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Link Type and Item.
        /// </summary>
        internal static string addLinkPleaseSelectLink {
            get {
                return ResourceManager.GetString("addLinkPleaseSelectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon aras {
            get {
                object obj = ResourceManager.GetObject("aras", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has been locked by someone..
        /// </summary>
        internal static string Aras_Server_Core_ItemIsLockedBySomeoneElseException {
            get {
                return ResourceManager.GetString("Aras_Server_Core_ItemIsLockedBySomeoneElseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link cannot be created..
        /// </summary>
        internal static string canNotCreateLink {
            get {
                return ResourceManager.GetString("canNotCreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is released, cannot link to it.
        /// </summary>
        internal static string canNotLinkReleasedItem {
            get {
                return ResourceManager.GetString("canNotLinkReleasedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create {0} - {1} structure because the relationship item does not have the &quot;external_id&quot; property.
        /// </summary>
        internal static string cantCreateFileRelation {
            get {
                return ResourceManager.GetString("cantCreateFileRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find {0} property &quot;{1}&quot; for mapping, it will be ignored.
        /// </summary>
        internal static string cantFindProperty {
            get {
                return ResourceManager.GetString("cantFindProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get {0} property info for mapping. {2}.
        /// </summary>
        internal static string cantGetPropertyInfo {
            get {
                return ResourceManager.GetString("cantGetPropertyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Refresh….
        /// </summary>
        internal static string clickRefresh {
            get {
                return ResourceManager.GetString("clickRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection does not contains passed value..
        /// </summary>
        internal static string CollectionNotContainsValue {
            get {
                return ResourceManager.GetString("CollectionNotContainsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item of the MSO_CommonSettings type is not present or these items are too much in Innovator..
        /// </summary>
        internal static string commonSettingsPreferenceError {
            get {
                return ResourceManager.GetString("commonSettingsPreferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current file needs to be closed to perform this operation.  OK to close current file and open latest version from Aras?  Any local changes will be lost.
        /// </summary>
        internal static string currentDocumentsNeedsToBeClosed {
            get {
                return ResourceManager.GetString("currentDocumentsNeedsToBeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current file need to be closed to perform this operation. Click OK to close current file and open selected version from Aras? Any local changes will be lost.
        /// </summary>
        internal static string currentDocumentsNeedsToBeClosedOpenNonLatest {
            get {
                return ResourceManager.GetString("currentDocumentsNeedsToBeClosedOpenNonLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item of the MSO_DefaultFileTypes type for {0} application is not present or these items are too much in Innovator. .
        /// </summary>
        internal static string defaultFileTypesPreferenceError {
            get {
                return ResourceManager.GetString("defaultFileTypesPreferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to detach from Aras?.
        /// </summary>
        internal static string detach {
            get {
                return ResourceManager.GetString("detach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Aras Document.
        /// </summary>
        internal static string dialogTitleNewDocumentNew {
            get {
                return ResourceManager.GetString("dialogTitleNewDocumentNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Aras.
        /// </summary>
        internal static string dialogTitleNewDocumentSave {
            get {
                return ResourceManager.GetString("dialogTitleNewDocumentSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As to Aras.
        /// </summary>
        internal static string dialogTitleNewDocumentSaveAs {
            get {
                return ResourceManager.GetString("dialogTitleNewDocumentSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes you made to &apos;{0}&apos;?.
        /// </summary>
        internal static string documentHasChanges_WantToSave {
            get {
                return ResourceManager.GetString("documentHasChanges_WantToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is locked by another user.
        /// </summary>
        internal static string documentIsLockedByAnotherUser {
            get {
                return ResourceManager.GetString("documentIsLockedByAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is locked by another user. Open it for view?.
        /// </summary>
        internal static string documentIsLockedByAnotherUserOpenForView {
            get {
                return ResourceManager.GetString("documentIsLockedByAnotherUserOpenForView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is not locked, lock it now?.
        /// </summary>
        internal static string documentIsNotLocked {
            get {
                return ResourceManager.GetString("documentIsNotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save MS Office document.
        /// </summary>
        internal static string documentIsNotSaved {
            get {
                return ResourceManager.GetString("documentIsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is not saved to Aras.
        /// </summary>
        internal static string documentIsNotSavedToAras {
            get {
                return ResourceManager.GetString("documentIsNotSavedToAras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating New Document failure..
        /// </summary>
        internal static string documentNewFailure {
            get {
                return ResourceManager.GetString("documentNewFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Numbering is unknown.
        /// </summary>
        internal static string documentNumberingIsUnknown {
            get {
                return ResourceManager.GetString("documentNumberingIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to lock the Document, OK to open the file for view only?.
        /// </summary>
        internal static string documentReleasedOrLockedOpenView {
            get {
                return ResourceManager.GetString("documentReleasedOrLockedOpenView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document save failure..
        /// </summary>
        internal static string documentSaveFailure {
            get {
                return ResourceManager.GetString("documentSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type &quot;{0}&quot; of Master Item Type &quot;{1}&quot; is not found! Please check Office Preference.
        /// </summary>
        internal static string documentTypeIsNotFound {
            get {
                return ResourceManager.GetString("documentTypeIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type doesn&apos;t support {0} property. Please check Office Preference.
        /// </summary>
        internal static string documentTypeNotSupportProperty {
            get {
                return ResourceManager.GetString("documentTypeNotSupportProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type “{0}” is not configured properly for use with Office Connector (Number is defined as Sequence).  Please contact your administrator..
        /// </summary>
        internal static string DocumentTypeNumberIsDefinedAsSequence {
            get {
                return ResourceManager.GetString("DocumentTypeNumberIsDefinedAsSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item of the {0} type with ID=&quot;{1}&quot; is not present..
        /// </summary>
        internal static string documentTypePreferenceError {
            get {
                return ResourceManager.GetString("documentTypePreferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document item with &apos;{0}&apos; number already exist.
        /// </summary>
        internal static string documentWithNumberAlreadyExists {
            get {
                return ResourceManager.GetString("documentWithNumberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string editButtonText {
            get {
                return ResourceManager.GetString("editButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ellipsis {
            get {
                object obj = ResourceManager.GetObject("Ellipsis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection can&apos;t be empty..
        /// </summary>
        internal static string EmptyCollectionException {
            get {
                return ResourceManager.GetString("EmptyCollectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is released and cannot be modified.
        /// </summary>
        internal static string errorReleased {
            get {
                return ResourceManager.GetString("errorReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Excel can&apos;t open two workbooks with the same name at the same time..
        /// </summary>
        internal static string excelCantOpenWBWithSameName {
            get {
                return ResourceManager.GetString("excelCantOpenWBWithSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document save failure. Cell name “{0}” not found..
        /// </summary>
        internal static string excelCellNotFound {
            get {
                return ResourceManager.GetString("excelCellNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email_attachment.
        /// </summary>
        internal static string external_id_emailAttachment {
            get {
                return ResourceManager.GetString("external_id_emailAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to native.
        /// </summary>
        internal static string external_id_nativeFile {
            get {
                return ResourceManager.GetString("external_id_nativeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viewable.
        /// </summary>
        internal static string external_id_viewableFile {
            get {
                return ResourceManager.GetString("external_id_viewableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aras.Document.MS-Office.
        /// </summary>
        internal static string external_owner {
            get {
                return ResourceManager.GetString("external_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file name can&apos;t contain any of the following characters:{0}.
        /// </summary>
        internal static string file_name_cant_contain_illegal_character {
            get {
                return ResourceManager.GetString("file_name_cant_contain_illegal_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have insufficient permissions.
        /// </summary>
        internal static string HaveNotInsufficientPermission {
            get {
                return ResourceManager.GetString("HaveNotInsufficientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.aras.com/help/office/11-0r4/.
        /// </summary>
        internal static string helpUrl {
            get {
                return ResourceManager.GetString("helpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_locked {
            get {
                object obj = ResourceManager.GetObject("img_locked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_locked_else {
            get {
                object obj = ResourceManager.GetObject("img_locked_else", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Document Number. Document Number can&apos;t contain invalid file name or only space characters if it used for file naming for current type. Please enter correct Document Number or contact to your administrator..
        /// </summary>
        internal static string incorrectDocumentNumberFileName {
            get {
                return ResourceManager.GetString("incorrectDocumentNumberFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification {0} does not contains selected link item in valid link item collection..
        /// </summary>
        internal static string InvalidLinkItemForClassification {
            get {
                return ResourceManager.GetString("InvalidLinkItemForClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is already linked.
        /// </summary>
        internal static string itemIsAlreadyLinked {
            get {
                return ResourceManager.GetString("itemIsAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is not found.
        /// </summary>
        internal static string itemNotFound {
            get {
                return ResourceManager.GetString("itemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep local changes?.
        /// </summary>
        internal static string keepLocalChanges {
            get {
                return ResourceManager.GetString("keepLocalChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keysearch {
            get {
                object obj = ResourceManager.GetObject("keysearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Aras subscriber license is required.
        /// </summary>
        internal static string licenseError {
            get {
                return ResourceManager.GetString("licenseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item &quot;{0}&quot; was selected for linking, but currently cannot be locked or updated by you.  Click OK to continue saving without the link to this item, or cancel to abort the save..
        /// </summary>
        internal static string LinkItemLocked {
            get {
                return ResourceManager.GetString("LinkItemLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more selected for linking items cannot be locked or updated by you..
        /// </summary>
        internal static string LinkItemsAreUnAvailable {
            get {
                return ResourceManager.GetString("LinkItemsAreUnAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should lock document before edit link items..
        /// </summary>
        internal static string lockDocumentPropose {
            get {
                return ResourceManager.GetString("lockDocumentPropose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose local changes?.
        /// </summary>
        internal static string loseLocalChanges {
            get {
                return ResourceManager.GetString("loseLocalChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aras Office Connector.
        /// </summary>
        internal static string messageBoxTitle {
            get {
                return ResourceManager.GetString("messageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        internal static string messageBoxTitleSaveAndClose {
            get {
                return ResourceManager.GetString("messageBoxTitleSaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newsearch {
            get {
                object obj = ResourceManager.GetObject("newsearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next_page {
            get {
                object obj = ResourceManager.GetObject("next_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document contains no files.
        /// </summary>
        internal static string noDocumentAttached {
            get {
                return ResourceManager.GetString("noDocumentAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no documents linked to this item..
        /// </summary>
        internal static string NoDocumentLinked {
            get {
                return ResourceManager.GetString("NoDocumentLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No links allowed.
        /// </summary>
        internal static string noLinksAllowed {
            get {
                return ResourceManager.GetString("noLinksAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap off2013_innovator {
            get {
                object obj = ResourceManager.GetObject("off2013_innovator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap off2013_keysearch {
            get {
                object obj = ResourceManager.GetObject("off2013_keysearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap off2013_locked {
            get {
                object obj = ResourceManager.GetObject("off2013_locked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap off2013_locked_else {
            get {
                object obj = ResourceManager.GetObject("off2013_locked_else", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap off2013_newsearch {
            get {
                object obj = ResourceManager.GetObject("off2013_newsearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap off2013_next_page {
            get {
                object obj = ResourceManager.GetObject("off2013_next_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap off2013_prev_page {
            get {
                object obj = ResourceManager.GetObject("off2013_prev_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Preference has errors:.
        /// </summary>
        internal static string OfficePreferenceHasErrors {
            get {
                return ResourceManager.GetString("OfficePreferenceHasErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An older version of this file exists in your local working directory. If you continue, the local file will be lost. OK to continue?.
        /// </summary>
        internal static string olderVersionOfThisFileExists {
            get {
                return ResourceManager.GetString("olderVersionOfThisFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one link item with foreign data source can be added..
        /// </summary>
        internal static string oneLinkWithForeignDataSource {
            get {
                return ResourceManager.GetString("oneLinkWithForeignDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more required properties are not mapped for setting by the user. Please contact your administrator to resolve this..
        /// </summary>
        internal static string oneOrMoreRequiredProperiesAreNotMapped {
            get {
                return ResourceManager.GetString("oneOrMoreRequiredProperiesAreNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more required properties are not set. Please provide values for all properties marked with a blue background..
        /// </summary>
        internal static string oneOrMoreRequiredProperiesAreSet {
            get {
                return ResourceManager.GetString("oneOrMoreRequiredProperiesAreSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your local file version is outdated compared to Aras.  You must update to the latest version before performing this operation.
        /// </summary>
        internal static string outOfDateOnLinkEdit {
            get {
                return ResourceManager.GetString("outOfDateOnLinkEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your local file version is outdated compared to Aras.  Unable to Lock the Document..
        /// </summary>
        internal static string outOfDateOnLock {
            get {
                return ResourceManager.GetString("outOfDateOnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your local file version is outdated compared to Aras.  If you need to save your existing file edits to Aras, you must first &quot;save as&quot; locally, then open the most recent version from Aras and manually merge the two files..
        /// </summary>
        internal static string outOfDateOnSave {
            get {
                return ResourceManager.GetString("outOfDateOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must be greater than zero..
        /// </summary>
        internal static string ParamGreterThanZero {
            get {
                return ResourceManager.GetString("ParamGreterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check Office Preference.
        /// </summary>
        internal static string PleaseCheckOfficePreference {
            get {
                return ResourceManager.GetString("PleaseCheckOfficePreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the document number.
        /// </summary>
        internal static string pleaseEnterTheDocumentNumber {
            get {
                return ResourceManager.GetString("pleaseEnterTheDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the file name.
        /// </summary>
        internal static string pleaseEnterTheFileName {
            get {
                return ResourceManager.GetString("pleaseEnterTheFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap prev_page {
            get {
                object obj = ResourceManager.GetObject("prev_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No promotions available.
        /// </summary>
        internal static string promoteStatesNotFound {
            get {
                return ResourceManager.GetString("promoteStatesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; property is required. You must provide a value for this property.
        /// </summary>
        internal static string property_required_provide_value {
            get {
                return ResourceManager.GetString("property_required_provide_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property  of the {1} type is null or is empty or is not correct. .
        /// </summary>
        internal static string propertyPreferenceError {
            get {
                return ResourceManager.GetString("propertyPreferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference with ID=&quot;{0}&quot; is not found. .
        /// </summary>
        internal static string referenceIsNotFound {
            get {
                return ResourceManager.GetString("referenceIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Link.
        /// </summary>
        internal static string removeLinkBoxTitle {
            get {
                return ResourceManager.GetString("removeLinkBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK to remove the link between {0} {1} and your Document?.
        /// </summary>
        internal static string removeLinkPrompt {
            get {
                return ResourceManager.GetString("removeLinkPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveUnlockClose_32 {
            get {
                object obj = ResourceManager.GetObject("SaveUnlockClose-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The active workbook must be closed to perform this operation.  OK to automatically save current changes and close?.
        /// </summary>
        internal static string saveWorkBookOnVersionChange {
            get {
                return ResourceManager.GetString("saveWorkBookOnVersionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search dialog - .
        /// </summary>
        internal static string searchDialogTitle {
            get {
                return ResourceManager.GetString("searchDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open from Aras.
        /// </summary>
        internal static string searchDialogTitleOpen {
            get {
                return ResourceManager.GetString("searchDialogTitleOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open from Linked Item.
        /// </summary>
        internal static string searchDialogTitleOpenFromLink {
            get {
                return ResourceManager.GetString("searchDialogTitleOpenFromLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Versions.
        /// </summary>
        internal static string searchDialogTitleOpenVersion {
            get {
                return ResourceManager.GetString("searchDialogTitleOpenVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected search contains the {0} field which is not present in the grid and its value could not be shown or changed there. Do you want to use it in this search?.
        /// </summary>
        internal static string selected_saved_search_is_not_compatible_with_current_grid_1 {
            get {
                return ResourceManager.GetString("selected_saved_search_is_not_compatible_with_current_grid_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected search contains some fields ({0}) which are not present in the grid and them values could not be shown or changed there. Do you want to use them in this search?.
        /// </summary>
        internal static string selected_saved_search_is_not_compatible_with_current_grid_8 {
            get {
                return ResourceManager.GetString("selected_saved_search_is_not_compatible_with_current_grid_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected search uses {0} search mode and could not be shown or changed. Do you want to use this search?.
        /// </summary>
        internal static string selected_saved_search_uses_noneditable_search_mode {
            get {
                return ResourceManager.GetString("selected_saved_search_uses_noneditable_search_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To State.
        /// </summary>
        internal static string stateColumnName {
            get {
                return ResourceManager.GetString("stateColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.aras.com/support.
        /// </summary>
        internal static string supportUrl {
            get {
                return ResourceManager.GetString("supportUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} with Type &apos;{1}&apos; is not supported.
        /// </summary>
        internal static string theDocumentWithTypeIsNotSupported {
            get {
                return ResourceManager.GetString("theDocumentWithTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no attached file of the correct type.
        /// </summary>
        internal static string thereIsNotAttachedFile {
            get {
                return ResourceManager.GetString("thereIsNotAttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is more than one attached file of the correct type.
        /// </summary>
        internal static string thereIsNotSingleAttachedFile {
            get {
                return ResourceManager.GetString("thereIsNotSingleAttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the latest version.
        /// </summary>
        internal static string thisIsTheLatestVersion {
            get {
                return ResourceManager.GetString("thisIsTheLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the existing item link to the current document.
        /// </summary>
        internal static string toolTipRemoveLinkItem {
            get {
                return ResourceManager.GetString("toolTipRemoveLinkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the linked item in the Aras web client.
        /// </summary>
        internal static string toolTipShowLinkItem {
            get {
                return ResourceManager.GetString("toolTipShowLinkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to attach File item to {0} item.
        /// </summary>
        internal static string unableAttachFileToDocument {
            get {
                return ResourceManager.GetString("unableAttachFileToDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to lock Document.
        /// </summary>
        internal static string unableToLockDocument {
            get {
                return ResourceManager.GetString("unableToLockDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url already in exist..
        /// </summary>
        internal static string urlAlreadyInExist {
            get {
                return ResourceManager.GetString("urlAlreadyInExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is not valid..
        /// </summary>
        internal static string urlIsNotValid {
            get {
                return ResourceManager.GetString("urlIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} Build {1}.
        /// </summary>
        internal static string versionAbout {
            get {
                return ResourceManager.GetString("versionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Connector client and server versions do not match client = {0}, server = {1}  Click OK to continue, Cancel to exit.
        /// </summary>
        internal static string VersionsDoNotMatch {
            get {
                return ResourceManager.GetString("VersionsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Connector client and server versions do not match.
        /// </summary>
        internal static string VersionsDoNotMatchCaption {
            get {
                return ResourceManager.GetString("VersionsDoNotMatchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a previously saved version of the current document, or compare versions..
        /// </summary>
        internal static string versionsSuperTipForWord {
            get {
                return ResourceManager.GetString("versionsSuperTipForWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.aras.com.
        /// </summary>
        internal static string visitUrl {
            get {
                return ResourceManager.GetString("visitUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to store Microsoft Office documents in Aras.  Please contact your administrator..
        /// </summary>
        internal static string youDontHaveAccessToStore {
            get {
                return ResourceManager.GetString("youDontHaveAccessToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select the item first.
        /// </summary>
        internal static string youMustSelectTheItemFirst {
            get {
                return ResourceManager.GetString("youMustSelectTheItemFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add supported itemtype to Office Preference.
        /// </summary>
        internal static string youNeedToAddItemtypesToMSOPreference {
            get {
                return ResourceManager.GetString("youNeedToAddItemtypesToMSOPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Document Type.
        /// </summary>
        internal static string youNeedToSelectDocumentType {
            get {
                return ResourceManager.GetString("youNeedToSelectDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Item required for this Document Type.
        /// </summary>
        internal static string youNeedToSelectLinkedItem {
            get {
                return ResourceManager.GetString("youNeedToSelectLinkedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template required for this Document Type.
        /// </summary>
        internal static string youNeedToSelectTemplate {
            get {
                return ResourceManager.GetString("youNeedToSelectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template and Linked Item required for this Document Type.
        /// </summary>
        internal static string youNeedToSelectTemplateAndLinkItem {
            get {
                return ResourceManager.GetString("youNeedToSelectTemplateAndLinkItem", resourceCulture);
            }
        }
    }
}
